### ISSUE TITLE
文件名内包含[或]时报错

### ISSUE THREAD

**Issue by InfinityBlue** [upyun/ruby-sdk#3]
您好。

由于fullpath中调用了decode，即使path之前已经将`[`和`]`转为`%5B`和`%5D`依然会被decode回来
```ruby
def fullpath(path)
  decoded = URI::encode(URI::decode(path.to_s.force_encoding('utf-8')))
  "/#{@bucket}#{decoded.start_with?('/') ? decoded : '/' + decoded}"
end
```

而`restclient`中又使用了`URI.parse`，当`[`或`]`出现在`?`之前时便会报错`URI::InvalidURIError: bad URI(is not URI?)`

暂时只想到了修改文件名一种办法，不知道有没有更好的方法？

**Comment by jsvisa** [comment]
@InfinityBlue 感谢您的反馈，我将尽快修复

**Comment by jsvisa** [comment]
@InfinityBlue 这个  issue 已经修复，先关闭了，如还有问题请重开
